cy2_pool = {
    'Body Talk[PAFF]': {'aliases': ['开门曲', '身体说话', '肢体语言', '肢体交流', '身体吹逼'], 'difficulty': [1, 11.5], 'artist': 'M2U',
                        'song_package': 'free'},
    'Survive[PAFF]': {'aliases': ['生存', '活着'], 'difficulty': [5, 10.25], 'artist': 'Kevin Penkin feat. Nikki Simmons',
                      'song_package': 'free'},
    'Bullet Waiting for Me[PAFF]': {'aliases': ['子弹', '子弹等我', '子弹杀我'], 'difficulty': [4, 11.5],
                                    'artist': 'Nikki Simmons', 'song_package': 'free'},
    'KANATA[PAFF]': {'aliases': ['かなた', '彼方'], 'difficulty': [6, 9.0], 'artist': 'mikito',
                     'song_package': 'free'},
    'KANATA(Glitch)[PAFF]': {'aliases': ['绿kanata'], 'difficulty': [11.75], 'artist': 'mikito',
                             'song_package': 'CAPSO!'},
    'Fight Another Day[PAFF]': {'aliases': ['fad', '择日再战'], 'difficulty': [6, 10.0], 'artist': 'Kat Penkin',
                                'song_package': 'free'},
    'Baptism of Fire[PAFF]': {'aliases': ['火洗'], 'difficulty': [7, 11.75], 'artist': 'Louise Penman',
                              'song_package': 'free'},
    'Fireflies[PAFF]': {'aliases': ['萤火虫'], 'difficulty': [6, 8.75], 'artist': 'Nikki Simmons', 'song_package': 'free'},
    'Gravity[PAFF]': {'aliases': ['重力', '高昏'], 'difficulty': [7, 13.0], 'artist': 'M2U', 'song_package': 'free'},
    'Gravity(Glitch)[PAFF]': {'aliases': [], 'difficulty': [13.5], 'artist': 'M2U', 'song_package': 'CAPSO!'},
    'Re:Boost[PAFF]': {'aliases': [], 'difficulty': [5, 11.25], 'artist': 'EAjRock', 'song_package': 'free'},
    'Re:Boost(Glitch)[PAFF]': {'aliases': [], 'difficulty': [13.0], 'artist': 'EAjRock', 'song_package': 'CAPSO!'},
    'Green Hope[PAFF]': {'aliases': ['绿屎', '绿希望'], 'difficulty': [7, 11.25], 'artist': 'Re:Brych voc. Sing Sing Rabbit',
                         'song_package': 'free'},
    'Under the same sky[PAFF]': {'aliases': [], 'difficulty': [7, 8.75], 'artist': 'hinode', 'song_package': 'free'},
    'So In Love[PAFF]': {'aliases': ['爱心'], 'difficulty': [7, 11.25], 'artist': 'MK&Kanae Asaba',
                         'song_package': 'Marvelous Mix vol.1'},
    'Winter Games[PAFF]': {'aliases': ['冬奥会'], 'difficulty': [6, 9.75],
                           'artist': 'GALAXIKA, MONO TO STEREO, TIGER DARROW', 'song_package': 'free'},
    'New World[PAFF]': {'aliases': ['生日歌', '新世界'], 'difficulty': [5, 10.25], 'artist': 'aioi feat. KAMATA JUNKO',
                        'song_package': 'free'},
    'SECRET;WEAPON[PAFF]': {'aliases': ['秘密武器', '秘武'], 'difficulty': [6, 13.75],
                            'artist': 'NOMA w/ Apo11o program ft.Yukacco', 'song_package': 'free'},
    'Lilac for Anabel[PAFF]': {'aliases': ['安娜贝尔'], 'difficulty': [8, 12.25],
                               'artist': 'Apo11o program ft.Mayumi Morinaga', 'song_package': 'free'},
    'Who Am I?[PAFF]': {'aliases': ['自报家门'], 'difficulty': [7, 10.25], 'artist': 'Iris feat. Ruri Matsumura',
                        'song_package': 'free'},
    'More Than Diamond[PAFF]': {'aliases': ['钻石', '💎'], 'difficulty': [6, 9.25], 'artist': 'THE SxPLAY(菅原紗由理)',
                                'song_package': 'free'},
    'Blossoms for Life[PAFF]': {'aliases': [], 'difficulty': [6, 11.75], 'artist': 'Shi Kuang Lee & Pico & 林子玹',
                                'song_package': 'free'},
    'Cityscape[PAFF]': {'aliases': ['城市', '🏙️'], 'difficulty': [5, 11.75],
                        'artist': 'Takashi OKAMOTO(12sound) feat. Tsukasa Shiraki',
                        'song_package': 'Featured Article Vol. 1'},
    'Favourites[PAFF]': {'aliases': ['最喜欢'], 'difficulty': [5, 10.5], 'artist': "DJ'TEKINA//SOMETHING",
                         'song_package': 'Featured Article Vol. 1'},
    'Make Me Alive[PAFF]': {'aliases': ['让我活'], 'difficulty': [8, 9.25], 'artist': 'THE SxPLAY(菅原紗由理)',
                            'song_package': 'Featured Article Vol. 1'},
    'Light up my love!![PAFF]': {'aliases': ['点爱', '亮爱', 'NOKIA'], 'difficulty': [9, 12.0],
                                 'artist': 'onoken feat. moco', 'song_package': 'Featured Article Vol. 1'},
    'Super Attractor[PAFF]': {'aliases': ['吸尘器'], 'difficulty': [6, 13.75], 'artist': 'ユアミトス',
                              'song_package': 'Featured Article Vol. 1'},
    'Recall[PAFF]': {'aliases': ['回忆'], 'difficulty': [5, 9.0], 'artist': 'Night Keepers', 'song_package': 'free'},
    'I Wish You Were Mine[PAFF]': {'aliases': ['希望你是我的'], 'difficulty': [7, 11.75], 'artist': 'GALAXIKA, ELIN',
                                   'song_package': 'Marvelous Mix vol.2'},
    'PIXIE DUST[PAFF]': {'aliases': ['皮鞋尘', 'p站尘'], 'difficulty': [5, 10.5], 'artist': '上村叶恵',
                         'song_package': 'Marvelous Mix vol.2'},
    'Sleeping Beast[PAFF]': {'aliases': ['睡兽', '昏睡野兽', '昏睡先辈'], 'difficulty': [7, 9.0], 'artist': 'SNoW',
                             'song_package': 'free'},
    'The Spark[NEKO#ΦωΦ]': {'aliases': ['火花', '星火'], 'difficulty': [8, 12.0],
                            'artist': 'Scott Brown & M-Project feat. Krystal', 'song_package': 'free'},
    'Resurrection[NEKO#ΦωΦ]': {'aliases': ['复活'], 'difficulty': [8, 12.0], 'artist': 'Kiryu', 'song_package': 'free'},
    'One Way Love[NEKO#ΦωΦ]': {'aliases': ['一路爱', '单恋'], 'difficulty': [6, 9.0], 'artist': 'Tsukasa',
                               'song_package': 'free'},
    'Happiness Breeze[NEKO#ΦωΦ]': {'aliases': ['快乐风'], 'difficulty': [7, 11.25], 'artist': '3R2 as DJ Mashiro',
                                   'song_package': 'free'},
    'Happiness Breeze(Glitch)[NEKO#ΦωΦ]': {'aliases': ['风吹绿我', '不快乐风'], 'difficulty': [14.25],
                                           'artist': '3R2 as DJ Mashiro', 'song_package': 'CAPSO!'},
    'Alterna Pt.1 -Cosmogony-[NEKO#ΦωΦ]': {'aliases': ['二重唱'], 'difficulty': [5, 11.5],
                                           'artist': 'Ayatsugu_Neverend ft.Kimi', 'song_package': 'free'},
    'Zealous Hearts[NEKO#ΦωΦ]': {'aliases': ['🍋', '柠檬心'], 'difficulty': [7, 11.0], 'artist': 'Zekk',
                                 'song_package': 'free'},
    'Keep it up[NEKO#ΦωΦ]': {'aliases': ['kiu'], 'difficulty': [8, 13.25], 'artist': 'uma', 'song_package': 'free'},
    'CODE NAME: GAMMA[NEKO#ΦωΦ]': {'aliases': ['cng', '伽马', 'gamma'], 'difficulty': [9, 14.75], 'artist': 'NeLiME',
                                   'song_package': 'free'},
    'Blow my mind[NEKO#ΦωΦ]': {'aliases': ['bmm', '葫芦歌', '吹我头'], 'difficulty': [9, 14.0], 'artist': '3R2',
                               'song_package': 'free'},
    'Chrome VOX[NEKO#ΦωΦ]': {'aliases': ['冲冲雷亚', 'vox', '浏览器', '谷歌'], 'difficulty': [9, 14.5],
                             'artist': 't+pazolite', 'song_package': 'free'},
    'Chrome VOX(Glitch)[NEKO#ΦωΦ]': {'aliases': ['冲绿雷亚'], 'difficulty': [15.5], 'artist': 't+pazolite',
                                     'song_package': 'CAPSO!'},
    'Hard Landing[NEKO#ΦωΦ]': {'aliases': ['硬着陆'], 'difficulty': [8, 11.0], 'artist': 'Yamajet',
                               'song_package': 'free'},
    'Brain Power[NEKO#ΦωΦ]': {'aliases': ['🧠', 'bp', '脑力', 'dssq', '脑裂'], 'difficulty': [8, 12.25], 'artist': 'NOMA',
                              'song_package': 'free'},
    'Sdorica The Story Unfolds[NEKO#ΦωΦ]': {'aliases': [], 'difficulty': [5, 10.25], 'artist': 'Sdorica',
                                            'song_package': 'free'},
    'Hesitant Blade[NEKO#ΦωΦ]': {'aliases': ['彷徨之刃', '膀胱之妊'], 'difficulty': [5, 12.0], 'artist': 'Sdorica',
                                 'song_package': 'free'},
    'Praystation[NEKO#ΦωΦ]': {'aliases': ['Pray', '祈祷站', '🙏🏻'], 'difficulty': [7, 13.75], 'artist': 'HiTECH NINJA',
                              'song_package': 'Game Disc vol.1'},
    '100sec Cat Dreams[NEKO#ΦωΦ]': {'aliases': ['百秒猫梦', '猫梦', '一百猫梦', '🐱'], 'difficulty': [8, 14.75],
                                    'artist': 'Ayatsugu_Revolved', 'song_package': 'Game Disc vol.1'},
    'REmorse[NEKO#ΦωΦ]': {'aliases': ['莫斯', '悔恨'], 'difficulty': [5, 14.5], 'artist': 'SIHanatsuka',
                          'song_package': 'Game Disc vol.1'},
    'Stranger[NEKO#ΦωΦ]': {'aliases': ['陌生人'], 'difficulty': [9, 11.75], 'artist': 'James Landino',
                           'song_package': 'Game Disc vol.1'},
    'extinguisher[NEKO#ΦωΦ]': {'aliases': ['灭火器', '🧯'], 'difficulty': [8, 11.0], 'artist': 'lixound',
                               'song_package': 'free'},
    'Online[NEKO#ΦωΦ]': {'aliases': ['上网', '冲浪'], 'difficulty': [7, 13.25], 'artist': 'HiTECH NINJA',
                         'song_package': 'Marvelous Mix vol.1'},
    'Sunday Night Blues[NEKO#ΦωΦ]': {'aliases': ['snb', '日晚蓝'], 'difficulty': [7, 9.75], 'artist': 'TERU FOX',
                                     'song_package': 'Marvelous Mix vol.1'},
    'FUJIN Rumble[NEKO#ΦωΦ]': {'aliases': ['风神', 'flick神'], 'difficulty': [7, 15.0],
                               'artist': 'COSIO(ZUNTATA) from GROOVE COASTER', 'song_package': 'free'},
    'Blow My Mind (tpz Overheat Remix)[NEKO#ΦωΦ]': {'aliases': ['bmmr', '升级葫芦', '吹我头'], 'difficulty': [9, 14.5],
                                                    'artist': '柳田Ethnica', 'song_package': 'Game Disc vol.2'},
    'For You the Bellz Toll[NEKO#ΦωΦ]': {'aliases': ['圣诞歌'], 'difficulty': [9, 14.25],
                                         'artist': '3R2 Remixed by t+pazolite', 'song_package': 'free'},
    'Maboroshi[NEKO#ΦωΦ]': {'aliases': ['抹布拉稀', '幻'], 'difficulty': [7, 13.75], 'artist': 'かめりあ(EDP)',
                            'song_package': 'Game Disc vol.2'},
    'TOKONOMA Spacewalk[NEKO#ΦωΦ]': {'aliases': ['太空漫步'], 'difficulty': [7, 12.75], 'artist': 't+pazolite',
                                     'song_package': 'Game Disc vol.2'},
    'UnNOT!CED[NEKO#ΦωΦ]': {'aliases': ['unnoticed'], 'difficulty': [7, 13.0], 'artist': 'V!C',
                            'song_package': 'Game Disc vol.2'},
    '下水鳴動して鼠一匹[NEKO#ΦωΦ]': {'aliases': ['老鼠', '🐭', '预判鼠', 'bga鞋垫'], 'difficulty': [9, 13.25], 'artist': 'O-SE',
                            'song_package': 'Game Disc vol.2'},
    "Capybara Kids' Paradise[NEKO#ΦωΦ]": {'aliases': ['水豚', '孩子天堂'], 'difficulty': [8, 14.75],
                                          'artist': 'Ice vs LunaticSounds', 'song_package': 'Marvelous Mix vol.2'},
    'Walnuts Walkers[NEKO#ΦωΦ]': {'aliases': ['坚果'], 'difficulty': [8, 13.0], 'artist': 'fether',
                                  'song_package': 'Marvelous Mix vol.3'},
    'Hydra[NEKO#ΦωΦ]': {'aliases': ['嗨爪', '🐍', '九头蛇', '水螅'], 'difficulty': [9, 12.0],
                        'artist': 'James Landino X Akira Complex', 'song_package': 'Battle CHAOS 2019'},
    'Hydra(Glitch)[NEKO#ΦωΦ]': {'aliases': ['九头蛇'], 'difficulty': [16.25], 'artist': 'James Landino X Akira Complex',
                                'song_package': 'Battle CHAOS 2019'},
    'Liberation[NEKO#ΦωΦ]': {'aliases': ['解放', 'lib'], 'difficulty': [9, 14.0], 'artist': 'Silaver & lixound',
                             'song_package': 'Battle CHAOS 2019'},
    'Liberation(Glitch)[NEKO#ΦωΦ]': {'aliases': ['4A', '得得得得得得', '没必要', '亏', '零块钱', '痛苦面具看起来十分痛苦'], 'difficulty': [15.75],
                                     'artist': 'Silaver & lixound', 'song_package': 'Battle CHAOS 2019'},
    'Ramen is God[NEKO#ΦωΦ]': {'aliases': ['🍜', '拉面神'], 'difficulty': [9, 14.5],
                               'artist': 'Ramenbot a.k.a Ice VS Masahiro "Godspeed" Aoki',
                               'song_package': 'Battle CHAOS 2019'},
    'Ramen is God(Glitch)[NEKO#ΦωΦ]': {'aliases': ['拉面神', '菠菜拉面'], 'difficulty': [16.25],
                                       'artist': 'Ramenbot a.k.a Ice VS Masahiro "Godspeed" Aoki',
                                       'song_package': 'Battle CHAOS 2019'},
    'Re:VeLΔTiØN ～光道ト破壞ノ雙白翼～[NEKO#ΦωΦ]': {'aliases': ['双白翼', '光道'], 'difficulty': [7, 14.25],
                                          'artist': 'Apo11o"月読命"program vs. NELiME OVERDRIVE',
                                          'song_package': 'Battle CHAOS 2019'},
    'Re:VeLΔTiØN ～光道ト破壞ノ雙白翼～(Glitch)[NEKO#ΦωΦ]': {'aliases': ['双白翼', '双绿翼'], 'difficulty': [16.0],
                                                  'artist': 'Apo11o"月読命"program vs. NELiME OVERDRIVE',
                                                  'song_package': 'Battle CHAOS 2019'},
    'Rebirth[NEKO#ΦωΦ]': {'aliases': ['重生', '绿道'], 'difficulty': [7, 11.75], 'artist': '3R2 & SIHanatsuka',
                          'song_package': 'Battle CHAOS 2019'},
    'Rebirth(Glitch)[NEKO#ΦωΦ]': {'aliases': [], 'difficulty': [15.5], 'artist': '3R2 & SIHanatsuka',
                                  'song_package': 'Battle CHAOS 2019'},
    'Rei[NEKO#ΦωΦ]': {'aliases': ['雷'], 'difficulty': [6, 12.25], 'artist': 'Catalyst', 'song_package': 'free'},
    '響け![NEKO#ΦωΦ]': {'aliases': ['响', 'hibiki', 'hibike'], 'difficulty': [8, 12.75], 'artist': 'Kry.exe',
                      'song_package': 'free'},
    '気楽なCloudy[NEKO#ΦωΦ]': {'aliases': ['气乐cloudy', '水果软糖'], 'difficulty': [8, 12.75],
                            'artist': 'technoplanet feat. はるの', 'song_package': 'free'},
    'Caliburne ~Story of the Legendary sword~[NEKO#ΦωΦ]': {'aliases': ['圣剑', '生煎', '咖喱棒'], 'difficulty': [9, 15.25],
                                                           'artist': 'Project Grimoire', 'song_package': 'maimai DX+'},
    "DON'T STOP ROCKIN'[NEKO#ΦωΦ]": {'aliases': ['不要停下来'], 'difficulty': [8, 12.5], 'artist': 'EB (aka EarBreaker)',
                                     'song_package': 'maimai DX+'},
    'Glorious Crown[NEKO#ΦωΦ]': {'aliases': ['👑', '皇冠', '黄瓜'], 'difficulty': [10, 16.25], 'artist': 'xi',
                                 'song_package': 'maimai DX+'},
    'Oshama Scramble![NEKO#ΦωΦ]': {'aliases': ['🥛', '牛奶', '我杀马', '哦杀马', '牛乳dance'], 'difficulty': [8, 14.0],
                                   'artist': 't+pazolite', 'song_package': 'maimai DX+'},
    '超常マイマイン[NEKO#ΦωΦ]': {'aliases': ['超常', '咕噜咕噜', '超常maimai'], 'difficulty': [8, 13.0], 'artist': 'ナユタン星人',
                          'song_package': 'maimai DX+'},
    'BlythE[NEKO#ΦωΦ]': {'aliases': [], 'difficulty': [8, 12.25], 'artist': 'M2U', 'song_package': 'DJ MAX vol.1'},
    'glory day[NEKO#ΦωΦ]': {'aliases': ['格劳瑞带', '荣耀日'], 'difficulty': [8, 11.75], 'artist': 'BEXTER x Mycin.T',
                            'song_package': 'DJ MAX vol.1'},
    'OBLIVION[NEKO#ΦωΦ]': {'aliases': ['遗忘'], 'difficulty': [7, 11.0], 'artist': 'ESTi',
                           'song_package': 'DJ MAX vol.1'},
    'Play The Future[NEKO#ΦωΦ]': {'aliases': ['玩未来'], 'difficulty': [5, 12.75], 'artist': 'Urbatonic Chopsticks',
                                  'song_package': 'DJ MAX vol.1'},
    "We're All Gonna Die[NEKO#ΦωΦ]": {'aliases': ['去死', '厕所', '撤硕', '扑街', '一起去死'], 'difficulty': [10, 15.5],
                                      'artist': 'Paul Bazooka', 'song_package': 'DJ MAX vol.1'},
    'Ask to Wind Live Mix[NEKO#ΦωΦ]': {'aliases': [], 'difficulty': [8, 10.25], 'artist': 'Forte Escape',
                                       'song_package': 'DJ MAX vol.2'},
    'End of the Moonlight[NEKO#ΦωΦ]': {'aliases': [], 'difficulty': [7, 12.5], 'artist': 'Forte Escape',
                                       'song_package': 'DJ MAX vol.2'},
    'Hello Pinky[NEKO#ΦωΦ]': {'aliases': [], 'difficulty': [7, 11.5], 'artist': 'NieN', 'song_package': 'DJ MAX vol.2'},
    'Nightmare[NEKO#ΦωΦ]': {'aliases': ['噩梦', '梦魇'], 'difficulty': [10, 15.5], 'artist': 'M2U',
                            'song_package': 'DJ MAX vol.2'},
    'U.A.D[NEKO#ΦωΦ]': {'aliases': ['uad'], 'difficulty': [7, 12.5], 'artist': 'HAYAKO',
                        'song_package': 'DJ MAX vol.2'},
    'Deadly Slot Game[ROBO_Head]': {'aliases': ['dsg', '老虎机', '大傻瓜'], 'difficulty': [7, 13.5], 'artist': '提供',
                                    'song_package': 'free'},
    'Deadly Slot Game(Glitch)[ROBO_Head]': {'aliases': ['乒乓球', '🏓'], 'difficulty': [14.0], 'artist': '提供',
                                            'song_package': 'CAPSO!'},
    'Make Me Burn[ROBO_Head]': {'aliases': ['mmb', '让我烧', '燃烧我'], 'difficulty': [6, 13.5], 'artist': 'JAKAZiD',
                                'song_package': 'free'},
    'Restriction[ROBO_Head]': {'aliases': ['制约'], 'difficulty': [7, 10.5], 'artist': 'Team Grimoire',
                               'song_package': 'free'},
    'Luolimasi[ROBO_Head]': {'aliases': ['萝莉马死', '白玫瑰', '洛丽玛丝'], 'difficulty': [7, 11.0], 'artist': 'SIHanatsuka',
                             'song_package': 'free'},
    'Claim the Game[ROBO_Head]': {'aliases': ['拍砖'], 'difficulty': [7, 11.75], 'artist': 'SOTUI feat. Tha Watcher',
                                  'song_package': 'free'},
    'Devilic Sphere[ROBO_Head]': {'aliases': ['恶魔球'], 'difficulty': [9, 13.0], 'artist': '3R2', 'song_package': 'free'},
    'Pure Powerstomper[ROBO_Head]': {'aliases': ['屁屁', 'pp'], 'difficulty': [8, 12.5],
                                     'artist': 'M-Project feat. Jonjo', 'song_package': 'free'},
    'Celestial Sounds[ROBO_Head]': {'aliases': ['天声'], 'difficulty': [8, 15.0], 'artist': '3R2',
                                    'song_package': 'free'},
    'Grimoire of Crimson[ROBO_Head]': {'aliases': ['红魔书'], 'difficulty': [8, 11.0], 'artist': 'Team Grimoire',
                                       'song_package': 'free'},
    'Dasein[ROBO_Head]': {'aliases': ['大山', '此在'], 'difficulty': [7, 13.25], 'artist': 'KIVΛ',
                          'song_package': 'free'},
    'Dasein(Glitch)[ROBO_Head]': {'aliases': ['劲爆五押'], 'difficulty': [14.0], 'artist': 'KIVΛ',
                                  'song_package': 'CAPSO!'},
    'CHAOS[ROBO_Head]': {'aliases': ['吵死', '打电话'], 'difficulty': [9, 14.75], 'artist': 'Æsir', 'song_package': 'free'},
    'EMber[ROBO_Head]': {'aliases': ['灰烬', '余烬'], 'difficulty': [7, 12.25], 'artist': 'SIHanatsuka',
                         'song_package': 'free'},
    'Midnight[ROBO_Head]': {'aliases': ['午夜', '午夜凶铃'], 'difficulty': [7, 14.0], 'artist': '提供', 'song_package': 'free'},
    'Dead Point[ROBO_Head]': {'aliases': ['死点'], 'difficulty': [8, 13.25], 'artist': 'Neutral Moon',
                              'song_package': 'free'},
    'Nocturnal Type[ROBO_Head]': {'aliases': ['夜行'], 'difficulty': [8, 11.25], 'artist': 'switchworks',
                                  'song_package': 'free'},
    'Sickest City[ROBO_Head]': {'aliases': ['病城'], 'difficulty': [7, 15.25], 'artist': 'DJ Myosuke',
                                'song_package': 'Memory Unit [A1]'},
    'Jazzy Glitch Machine[ROBO_Head]': {'aliases': ['爵士机', 'jgm', '金拱门'], 'difficulty': [8, 13.75], 'artist': '提供',
                                        'song_package': 'Memory Unit [A1]'},
    'dimensionalize nervous breakdown[ROBO_Head]': {'aliases': ['精神崩溃', '神经衰弱'], 'difficulty': [7, 13.75],
                                                    'artist': 'Frums', 'song_package': 'Memory Unit [A1]'},
    'cold[ROBO_Head]': {'aliases': ['冷', '企鹅', '🐧', 'Q币'], 'difficulty': [7, 11.75], 'artist': 'Noizenecio',
                        'song_package': 'Memory Unit [A1]'},
    'NRG_Tech[ROBO_Head]': {'aliases': ['牛肉干科技'], 'difficulty': [7, 13.25], 'artist': '3R2',
                            'song_package': 'Memory Unit [A1]'},
    'Break Through The Barrier[ROBO_Head]': {'aliases': ['bttb', '破壁'], 'difficulty': [8, 13.5], 'artist': 'lixound',
                                             'song_package': 'Marvelous Mix vol.1'},
    'Dead Master[ROBO_Head]': {'aliases': ['死大师'], 'difficulty': [9, 13.0], 'artist': 'Neutral Moon',
                               'song_package': 'Marvelous Mix vol.1'},
    'Accelerator[ROBO_Head]': {'aliases': ['加速器'], 'difficulty': [7, 14.0], 'artist': 'Massive New Krew',
                               'song_package': 'Memory Unit [A2]'},
    'Armaros[ROBO_Head]': {'aliases': [], 'difficulty': [8, 12.0], 'artist': 'Dj Grimoire',
                           'song_package': 'Memory Unit [A2]'},
    'Break The Core[ROBO_Head]': {'aliases': ['btc', '核心', '破核'], 'difficulty': [9, 13.5], 'artist': 'PTB10',
                                  'song_package': 'Memory Unit [A2]'},
    'Milky Way Galaxy[ROBO_Head]': {'aliases': ['银河系'], 'difficulty': [8, 13.0], 'artist': '3R2',
                                    'song_package': 'Memory Unit [A2]'},
    'ViRUS[ROBO_Head]': {'aliases': ['病毒', '噬菌体', '🦠'], 'difficulty': [8, 11.75], 'artist': 'Deepshout',
                         'song_package': 'Memory Unit [A2]'},
    'Awakening[ROBO_Head]': {'aliases': ['阿姨压一压'], 'difficulty': [5, 10.5], 'artist': 'DiagonalT',
                             'song_package': 'Marvelous Mix vol.2'},
    'Hagiasmos[ROBO_Head]': {'aliases': [], 'difficulty': [8, 12.75], 'artist': 'Iris',
                             'song_package': 'Marvelous Mix vol.2'},
    'Fade Into The Darkness[ROBO_Head]': {'aliases': [], 'difficulty': [9, 13.5], 'artist': 'SADA',
                                          'song_package': 'Marvelous Mix vol.3'},
    'SHIRO[ROBO_Head]': {'aliases': ['白'], 'difficulty': [6, 13.0], 'artist': 'James Landino',
                         'song_package': 'Marvelous Mix vol.3'},
    "Tunnef's Nightmare[ROBO_Head]": {'aliases': ['旧梦魇'], 'difficulty': [9, 14.0], 'artist': 'Neutral Moon',
                                      'song_package': 'Marvelous Mix vol.3'},
    'Reset[Ivy]': {'aliases': ['重置'], 'difficulty': [7, 12.25], 'artist': 'SIHanatsuka', 'song_package': 'free'},
    'D R G[Ivy]': {'aliases': ['drg', '大热狗', '删游戏'], 'difficulty': [6, 11.5], 'artist': 'onoken',
                   'song_package': 'free'},
    'Sentimental Journey[Ivy]': {'aliases': ['sj'], 'difficulty': [7, 14.0], 'artist': 'switchworks',
                                 'song_package': 'free'},
    'Biotonic[Ivy]': {'aliases': ['仿生'], 'difficulty': [7, 13.0], 'artist': 'onoken', 'song_package': 'free'},
    'Alexandrite[Ivy]': {'aliases': ['变石', '亚历山大'], 'difficulty': [7, 14.0], 'artist': 'onoken',
                         'song_package': 'free'},
    'Tokiwatari[Ivy]': {'aliases': ['托奇娃塔丽', '时渡'], 'difficulty': [7, 13.0], 'artist': 'Yamajet',
                        'song_package': 'free'},
    'Purge[Ivy]': {'aliases': ['肃清'], 'difficulty': [8, 12.25], 'artist': '3R2', 'song_package': 'free'},
    'Area184[Ivy]': {'aliases': [184], 'difficulty': [8, 11.75], 'artist': 'Persona', 'song_package': 'free'},
    'BloodyMare[Ivy]': {'aliases': ['血魔', 'BM'], 'difficulty': [8, 13.0], 'artist': 'Tatsh Assault X',
                        'song_package': 'free'},
    'AssaultMare[Ivy]': {'aliases': ['袭魔', 'AM', '袭击妈妈'], 'difficulty': [9, 14.25], 'artist': 'Tatsh Assault X',
                         'song_package': 'free'},
    'Lunar Mare[Ivy]': {'aliases': ['月魔', '月海'], 'difficulty': [8, 14.5], 'artist': 'xi vs sakuzyo',
                        'song_package': 'free'},
    '99 Glooms[Ivy]': {'aliases': ['99感冒灵', '99G', '结婚曲'], 'difficulty': [7, 13.75], 'artist': 'Sta',
                       'song_package': 'free'},
    'Pressure[Ivy]': {'aliases': ['压力', '压强'], 'difficulty': [7, 12.25], 'artist': 'Tsukasa', 'song_package': 'free'},
    'V.[Ivy]': {'aliases': ['V'], 'difficulty': [10, 15.5], 'artist': 'Æsir', 'song_package': 'free'},
    'Cristalisia[Ivy]': {'aliases': ['晶体'], 'difficulty': [6, 12.5], 'artist': 'onoken',
                         'song_package': 'Emotion Samples 01'},
    'Occidens[Ivy]': {'aliases': ['occ'], 'difficulty': [7, 14.5], 'artist': 'ginkiha',
                      'song_package': 'Emotion Samples 01'},
    'Red Five[Ivy]': {'aliases': ['红五', '红废物'], 'difficulty': [7, 13.75], 'artist': 'Cranky',
                      'song_package': 'Emotion Samples 01'},
    'CODENAME : SIGMA[Ivy]': {'aliases': ['死个妈', 'cns', '西格玛', '四个马'], 'difficulty': [9, 14.75], 'artist': 'NeLiME',
                              'song_package': 'Emotion Samples 02'},
    'New Challenger Approaching[Ivy]': {'aliases': ['新挑战者', 'nca'], 'difficulty': [8, 14.75], 'artist': 'かめりあ(EDP)',
                                        'song_package': 'Emotion Samples 02'},
    "What's Your PR.Ice?[Ivy]": {'aliases': ["what's your price", '舔ice', '您 值 几 个 价'], 'difficulty': [7, 11.75],
                                 'artist': 'SOTUI feat. Kry.exe', 'song_package': 'Emotion Samples 02'},
    'VIS::CRACKED[Ivy]': {'aliases': ['工地', 'vis', '建筑工地'], 'difficulty': [9, 15.75], 'artist': 'Frums',
                          'song_package': 'Emotion Samples 02'},
    'Wicked Ceremony[Ivy]': {'aliases': ['wc', '坏典礼'], 'difficulty': [8, 14.0], 'artist': 'Ice meets t+pazolite',
                             'song_package': 'Emotion Samples 02'},
    'Halloween Party[Ivy]': {'aliases': ['南瓜', '万圣节'], 'difficulty': [9, 15.25], 'artist': 'SHK',
                             'song_package': 'free'},
    'Bloody Purity[Ivy]': {'aliases': ['血纯'], 'difficulty': [8, 14.25], 'artist': 'eyemedia', 'song_package': 'CAPSO!'},
    'Masquerade[Ivy]': {'aliases': ['假面舞会', '假面'], 'difficulty': [7, 11.5], 'artist': 'M2U', 'song_package': 'CAPSO!'},
    'Quantum Labyrinth[Ivy]': {'aliases': ['量子迷宫'], 'difficulty': [7, 12.25], 'artist': 'Haloweak',
                               'song_package': 'CAPSO!'},
    'Saika[Ivy]': {'aliases': ['彩华'], 'difficulty': [7, 12.0], 'artist': 'Rabpit', 'song_package': 'CAPSO!'},
    'To Further Dream[Ivy]': {'aliases': ['🐴', '远梦'], 'difficulty': [7, 12.5], 'artist': 'Shinichi Kobayashi',
                              'song_package': 'CAPSO!'},
    'Libera Me[Ivy]': {'aliases': ['✝︎'], 'difficulty': [8, 13.5], 'artist': 'Cranky', 'song_package': 'CAPSO!'},
    'Qualia[Ivy]': {'aliases': ['夸俩'], 'difficulty': [9, 13.25], 'artist': 'KIVΛ', 'song_package': 'CAPSO!'},
    'DigiGroove[Ivy]': {'aliases': [], 'difficulty': [7, 12.75], 'artist': 'Electron',
                        'song_package': 'Emotion Samples 03'},
    'Heat Ring[Ivy]': {'aliases': ['热环'], 'difficulty': [7, 11.5], 'artist': 'James Landino',
                       'song_package': 'Emotion Samples 03'},
    'Leaving All Behind[Ivy]': {'aliases': ['lab'], 'difficulty': [7, 13.0], 'artist': 'NOMA feat. Kanata.N',
                                'song_package': 'Emotion Samples 03'},
    'Symmetry[Ivy]': {'aliases': ['td不会做难曲', '对称性', '对称'], 'difficulty': [9, 15.0], 'artist': 'SIHanatsuka',
                      'song_package': 'Emotion Samples 03'},
    'Time to Fight[Ivy]': {'aliases': ['ttf'], 'difficulty': [9, 14.0], 'artist': 'Paul Bazooka',
                           'song_package': 'Emotion Samples 03'},
    'conflict[Ivy]': {'aliases': ['公交车', '紫车'], 'difficulty': [9, 15.25], 'artist': 'siromaru + cranky',
                      'song_package': 'free'},
    'conflict(Glitch)[Ivy]': {'aliases': ['绿公交车', '绿车'], 'difficulty': [15.5], 'artist': 'siromaru + cranky',
                              'song_package': 'CAPSO!'},
    'FREEDOM DiVE[Ivy]': {'aliases': ['自由落体', 'fd'], 'difficulty': [10, 15.75], 'artist': 'xi',
                          'song_package': 'CAPSO!'},
    'Summer Zephyr[Ivy]': {'aliases': ['三岁萝莉'], 'difficulty': [6, 10.25], 'artist': 'SUi', 'song_package': 'free'},
    'Sovereign[Ivy]': {'aliases': [123], 'difficulty': [8, 13.0], 'artist': 'LureRabbit', 'song_package': 'free'},
    'Effervesce[Crystal PuNK]': {'aliases': ['泡腾'], 'difficulty': [6, 13.25], 'artist': 'MELOIMAGE',
                                 'song_package': 'free'},
    'Chandelier XIII[Crystal PuNK]': {'aliases': ['吊灯13', '吊灯十三'], 'difficulty': [6, 12.75], 'artist': 'Ring',
                                      'song_package': 'free'},
    'Sunshine Duration[Crystal PuNK]': {'aliases': ['阳光普照'], 'difficulty': [7, 12.25],
                                        'artist': 'Re:Brych VOC Sing Sing Rabbit', 'song_package': 'free'},
    'Deep Dive[Crystal PuNK]': {'aliases': ['dd'], 'difficulty': [6, 13.5], 'artist': 'MELOIMAGE',
                                'song_package': 'free'},
    'βinαrΨ[Crystal PuNK]': {'aliases': ['binary'], 'difficulty': [7, 12.25], 'artist': 'Ring', 'song_package': 'free'},
    'Dark Madness[Crystal PuNK]': {'aliases': ['黑噩梦'], 'difficulty': [7, 13.25], 'artist': 'Shi Kuang Lee',
                                   'song_package': 'free'},
    'The Cross[Crystal PuNK]': {'aliases': ['❌', '十', '+', '➕', '✝️'], 'difficulty': [6, 11.75], 'artist': 'Lyc',
                                'song_package': 'free'},
    'Darling Staring...[Crystal PuNK]': {'aliases': ['02の⭐'], 'difficulty': [7, 13.75],
                                         'artist': 'technoplanet feat. はるの', 'song_package': 'Marvelous Mix vol.3'},
    'Crimson Fate[Crystal PuNK]': {'aliases': ['绯红命运'], 'difficulty': [8, 13.0],
                                   'artist': 'tetsuyanao feat. ROXI CHEN(渣泥ZANI)', 'song_package': 'PuNK EP'},
    'Familiar Craze[Crystal PuNK]': {'aliases': [], 'difficulty': [8, 13.0], 'artist': 'MELOIMAGE',
                                     'song_package': 'PuNK EP'},
    'Malstream[Crystal PuNK]': {'aliases': ['恶流'], 'difficulty': [6, 12.25], 'artist': 'MELOIMAGE',
                                'song_package': 'PuNK EP'},
    'V.R.W[Crystal PuNK]': {'aliases': ['vrw'], 'difficulty': [6, 11.5], 'artist': 'カラスヤサボウ',
                            'song_package': 'PuNK EP'},
    'velkinta[Crystal PuNK]': {'aliases': [], 'difficulty': [6, 12.0], 'artist': 'EAjRock', 'song_package': 'PuNK EP'},
    'Anchor[Vanessa]': {'aliases': ['⚓', '锚'], 'difficulty': [5, 9.5],
                        'artist': 'Iris ft. Victor Kong & Ruri Matsumura', 'song_package': 'free'},
    'syuten[Vanessa]': {'aliases': [], 'difficulty': [5, 10.5], 'artist': 'Apo11o"COLLAPSAR"program ft.大瀬良あい',
                        'song_package': 'free'},
    'Rosa Rubus[Vanessa]': {'aliases': ['荼靡'], 'difficulty': [6, 11.0], 'artist': 'SIHanatsuka',
                            'song_package': 'free'},
    'XYZ[Vanessa]': {'aliases': ['小姨子', '小燕子', '小鸭子', 'joe极致美臀'], 'difficulty': [9, 15.25], 'artist': 'technoplanet',
                     'song_package': 'free'},
    'II-V[Vanessa]': {'aliases': ['二五', 25], 'difficulty': [7, 12.0], 'artist': 'Ring', 'song_package': 'free'},
    'Chaos and Abyss -3rd Movement-[Vanessa]': {'aliases': ['交互博物馆', 'caa'], 'difficulty': [10, 14.5],
                                                'artist': 'Ayatsugu_Revolved', 'song_package': 'free'},
    'Duality[Vanessa]': {'aliases': [], 'difficulty': [8, 11.0], 'artist': '3R2', 'song_package': 'free'},
    'Ra[Vanessa]': {'aliases': [], 'difficulty': [8, 12.25], 'artist': '溝口ゆうま feat. テヅカ', 'song_package': 'free'},
    'CHAOS //System Offline//[Vanessa]': {'aliases': ['交响chaos', 'chaos交响', '掉线chaos'], 'difficulty': [8, 12.5],
                                          'artist': 'Cytus', 'song_package': 'free'},
    'V. //System Offline//[Vanessa]': {'aliases': ['交响v', 'v交响', '掉线v'], 'difficulty': [8, 13.0], 'artist': 'Cytus',
                                       'song_package': 'free'},
    'II[Vanessa]': {'aliases': [2, '马拉松', '八分钟', 'll'], 'difficulty': [9, 15.0], 'artist': 'Cytus', 'song_package': 'free'},
    'Used to be[Vanessa]': {'aliases': ['utb'], 'difficulty': [5, 9.75], 'artist': 'KIVΛ', 'song_package': 'free'},
    'The Whole Rest[Vanessa]': {'aliases': ['twr', 'op', '全休止符'], 'difficulty': [7, 12.25], 'artist': 'KIVΛ',
                                'song_package': 'free'},
    'AIAIAI[Kizuna AI]': {'aliases': ['爱爱爱'], 'difficulty': [8, 11.5], 'artist': 'Kizuna AI',
                          'song_package': 'Kizuna AI'},
    'Hello, Morning[Kizuna AI]': {'aliases': ['早上好'], 'difficulty': [7, 12.25], 'artist': 'Kizuna AI',
                                  'song_package': 'Kizuna AI'},
    'future base[Kizuna AI]': {'aliases': [], 'difficulty': [6, 11.25], 'artist': 'Kizuna AI',
                               'song_package': 'Kizuna AI'},
    'new world[Kizuna AI]': {'aliases': ['新世界'], 'difficulty': [7, 11.0], 'artist': 'Kizuna AI',
                             'song_package': 'Kizuna AI'},
    'miracle step[Kizuna AI]': {'aliases': [], 'difficulty': [5, 11.25], 'artist': 'Kizuna AI',
                                'song_package': 'Kizuna AI'},
    'meet you[Kizuna AI]': {'aliases': ['遇见你'], 'difficulty': [5, 12.25], 'artist': 'Kizuna AI',
                            'song_package': 'Kizuna AI'},
    'mirai[Kizuna AI]': {'aliases': ['未来'], 'difficulty': [6, 9.5], 'artist': 'Kizuna AI', 'song_package': 'Kizuna AI'},
    'over the reality[Kizuna AI]': {'aliases': ['超越现实'], 'difficulty': [7, 12.25], 'artist': 'Kizuna AI',
                                    'song_package': 'Kizuna AI'},
    'melty world[Kizuna AI]': {'aliases': ['融化世界'], 'difficulty': [8, 13.0], 'artist': 'Kizuna AI',
                               'song_package': 'Kizuna AI'},
    'hello, alone[Kizuna AI]': {'aliases': ['你好孤儿'], 'difficulty': [6, 10.0], 'artist': 'Kizuna AI',
                                'song_package': 'Kizuna AI'},
    'Blue Star[Miku]': {'aliases': ['蓝星'], 'difficulty': [6, 10.0], 'artist': '八王子P', 'song_package': 'Miku'},
    'BREAK IT[Miku]': {'aliases': ['打破它'], 'difficulty': [8, 13.0], 'artist': '雄之助', 'song_package': 'Miku'},
    "Can't Make a Song!![Miku]": {'aliases': ['不会写歌'], 'difficulty': [7, 11.25], 'artist': 'beat_shobon',
                                  'song_package': 'Miku'},
    'Miku[Miku]': {'aliases': ['我婆'], 'difficulty': [6, 10.0], 'artist': 'Anamanaguchi', 'song_package': 'Miku'},
    'Sharing The World[Miku]': {'aliases': ['分享砸瓦鲁多', '分享世界'], 'difficulty': [6, 9.25], 'artist': 'BIGHEAD',
                                'song_package': 'Miku'},
    'Venus di Ujung Jari[Miku]': {'aliases': [], 'difficulty': [5, 7.0], 'artist': 'mohax (VOCALO.ID)',
                                  'song_package': 'Miku'},
    'ラッキー☆オーブ[Miku]': {'aliases': ['lucky orb'], 'difficulty': [7, 10.75], 'artist': 'emon(Tes.)',
                       'song_package': 'Miku'},
    '魔法みたいなミュージック！[Miku]': {'aliases': ['魔法'], 'difficulty': [7, 13.0], 'artist': 'OSTER project',
                            'song_package': 'Miku'},
    '月西江[Miku]': {'aliases': [], 'difficulty': [5, 8.0], 'artist': 'solpie', 'song_package': 'Miku'},
    'Ten Thousand Stars[Miku]': {'aliases': ['万星'], 'difficulty': [6, 12.5], 'artist': 'CircusP',
                                 'song_package': 'Miku'},
    'Glass Wall[Miku]': {'aliases': ['玻璃墙'], 'difficulty': [6, 10.25], 'artist': 'GuitarHeroPianoZero',
                         'song_package': 'Miku'},
    'Cybernetic[Miku]': {'aliases': ['赛博', '控制论'], 'difficulty': [7, 13.5], 'artist': '雄之助 × Circus-P',
                         'song_package': 'Miku'},
    'Decade[Miku]': {'aliases': ['帝骑', '十年'], 'difficulty': [6, 8.75], 'artist': 'Dixie Flatline',
                     'song_package': 'Miku'},
    'ラッキー☆オーブ (3R2 Remix)[Miku]': {'aliases': ['orb 3r2', 'lucky orb remix'], 'difficulty': [7, 10.75],
                                   'artist': 'emon(Tes.)', 'song_package': 'Miku'},
    'INSPION[Xenon]': {'aliases': [], 'difficulty': [9, 13.0], 'artist': 'INSPION', 'song_package': 'Xenon'},
    'Whisper in my Head[Xenon]': {'aliases': ['爱嘶吼'], 'difficulty': [7, 13.0], 'artist': 'AssHoleBand',
                                  'song_package': 'Xenon'},
    'Return[Xenon]': {'aliases': ['回来', '回归', '还我'], 'difficulty': [6, 11.0], 'artist': 'L DERCoLoR',
                      'song_package': 'Xenon'},
    'concentric circles[Xenon]': {'aliases': ['同心圆'], 'difficulty': [7, 12.25], 'artist': 'Yichen',
                                  'song_package': 'Xenon'},
    'Fighting[Xenon]': {'aliases': [], 'difficulty': [7, 11.5], 'artist': 'Claymore', 'song_package': 'Xenon'},
    'To the Light[Xenon]': {'aliases': [], 'difficulty': [8, 13.0], 'artist': 'FUTURE AFTER A SECOND',
                            'song_package': 'Xenon'},
    'Phantom Razor[Xenon]': {'aliases': ['幻影剃须刀', '刀片'], 'difficulty': [8, 12.75], 'artist': 'Daisuke Kurosawa',
                             'song_package': 'Xenon'},
    'Phantom Razor(Glitch)[Xenon]': {'aliases': [], 'difficulty': [14.25], 'artist': 'Daisuke Kurosawa',
                                     'song_package': 'Xenon & CAPSO!'},
    'Black Hole[Xenon]': {'aliases': ['黑洞', 'py（问题发言）'], 'difficulty': [4, 9.75], 'artist': 'A-Tse & KIVΛ',
                          'song_package': 'Xenon'},
    'Samurai[Xenon]': {'aliases': ['武士'], 'difficulty': [9, 14.0], 'artist': 'Kobayashi Project',
                       'song_package': 'Xenon'},
    'IOLITE-SUNSTONE[Xenon]': {'aliases': ['石头歌'], 'difficulty': [7, 10.75],
                               'artist': 'Hideyuki Ono x Daisuke Kurosawa', 'song_package': 'Xenon'},
    'Sairai[Xenon]': {'aliases': ['再来'], 'difficulty': [5, 9.5], 'artist': 'Shinichi Kobayashi',
                      'song_package': 'Xenon'},
    'Ultimate[Xenon]': {'aliases': ['放课后'], 'difficulty': [8, 13.0], 'artist': 'やいり', 'song_package': 'Xenon'},
    'Karma[Xenon]': {'aliases': ['恶果'], 'difficulty': [7, 11.25], 'artist': 'OBSESS', 'song_package': 'Xenon'},
    'Chosen[Xenon]': {'aliases': ['既定印象'], 'difficulty': [7, 13.0], 'artist': '既定印象', 'song_package': 'Xenon'},
    'Violet[Xenon]': {'aliases': ['薇尔莉特', '紫罗兰'], 'difficulty': [7, 15.0], 'artist': 'Yohei Kimura',
                      'song_package': 'Xenon'},
    'Asylum[Xenon]': {'aliases': ['疯人院'], 'difficulty': [7, 12.25], 'artist': 'Zangief', 'song_package': 'Xenon'},
    'Xiorc[ConneR]': {'aliases': ['架字十'], 'difficulty': [10, 13.5], 'artist': 'Team Grimoire+あま猫',
                      'song_package': 'ConneR'},
    'REBELLIUM[ConneR]': {'aliases': ['REBE', '热波'], 'difficulty': [9, 14.5], 'artist': 'Section9',
                          'song_package': 'ConneR'},
    'Imprinting[ConneR]': {'aliases': ['印记', 'imp', '刻印', '复印机'], 'difficulty': [8, 12.5], 'artist': 'Sakuzyo',
                           'song_package': 'ConneR'},
    'Imprinting(Glitch)[ConneR]': {'aliases': ['大粪印记', '粪记', '粪'], 'difficulty': [15.0], 'artist': 'Sakuzyo',
                                   'song_package': 'ConneR & CAPSO!'},
    'Gekkouka[ConneR]': {'aliases': ['月光曲'], 'difficulty': [8, 11.5], 'artist': 'Masanori Akita',
                         'song_package': 'ConneR'},
    'Light of Buenos Aires[ConneR]': {'aliases': ['布宜诺斯艾利斯', '阿根廷之光'], 'difficulty': [7, 11.75],
                                      'artist': 'Masanori Akita', 'song_package': 'ConneR'},
    'tondari-hanetari[ConneR]': {'aliases': ['t-h', '飞跳'], 'difficulty': [8, 13.0], 'artist': 'Yuichi Tsuchiya',
                                 'song_package': 'ConneR'},
    'Abduction[ConneR]': {'aliases': ['诱拐', '溯因'], 'difficulty': [8, 11.0], 'artist': 'VILA', 'song_package': 'ConneR'},
    'I luv U[ConneR]': {'aliases': ['i love you', '表白歌', '我爱你'], 'difficulty': [7, 10.0], 'artist': 'SQUAR',
                        'song_package': 'ConneR'},
    'Instinct[ConneR]': {'aliases': ['本能'], 'difficulty': [8, 11.5], 'artist': 'Sakuzyo', 'song_package': 'ConneR'},
    'Aphasia[ConneR]': {'aliases': ['失语症'], 'difficulty': [7, 12.75], 'artist': 'Team Grimoire',
                        'song_package': 'ConneR'},
    'Olympia[ConneR]': {'aliases': ['奥林匹亚', '奥运'], 'difficulty': [6, 12.0], 'artist': 'Nardis',
                        'song_package': 'ConneR'},
    'Demetrius[ConneR]': {'aliases': ['deme'], 'difficulty': [6, 13.0], 'artist': 'James Landino',
                          'song_package': 'ConneR'},
    "L'Ultima Cena[ConneR]": {'aliases': ['兔子', '🐰'], 'difficulty': [8, 13.25], 'artist': 'Laur',
                              'song_package': 'ConneR'},
    'Deus Ex Machina[ConneR]': {'aliases': ['机械降神'], 'difficulty': [8, 12.5], 'artist': 'Powerless',
                                'song_package': 'ConneR'},
    'Fur War, Pur War[ConneR]': {'aliases': ['防蚊喷雾', 'fwpw'], 'difficulty': [8, 15.25], 'artist': 'N.M.S.T.',
                                 'song_package': 'ConneR'},
    'LEVEL4[Cherry]': {'aliases': ['考四级'], 'difficulty': [7, 13.0], 'artist': '空野青空', 'song_package': 'Cherry'},
    'Living for you[Cherry]': {'aliases': ['为你而生'], 'difficulty': [7, 11.25], 'artist': 'Kat Penkin',
                               'song_package': 'Cherry'},
    "I'M NOT[Cherry]": {'aliases': ['我不是'], 'difficulty': [6, 10.75], 'artist': 'nowhere 此時刻',
                        'song_package': 'Cherry'},
    'Stop at nothing[Cherry]': {'aliases': [], 'difficulty': [7, 11.0], 'artist': 'Kat Penkin',
                                'song_package': 'Cherry'},
    'RETRIEVE[Cherry]': {'aliases': [], 'difficulty': [7, 11.25], 'artist': 'MELOIMAGE', 'song_package': 'Cherry'},
    'Still[Cherry]': {'aliases': ['刀', '你唱得真难听', '刀子'], 'difficulty': [6, 11.0], 'artist': 'Rua feat. K',
                      'song_package': 'Cherry'},
    'CREDENCE[Cherry]': {'aliases': ['信赖度'], 'difficulty': [8, 11.25], 'artist': 'MELOIMAGE',
                         'song_package': 'Cherry'},
    'CREDENCE(Glitch)[Cherry]': {'aliases': [], 'difficulty': [13.0], 'artist': 'MELOIMAGE',
                                 'song_package': 'Cherry & CAPSO!'},
    'SYSTEMFEIT[Cherry]': {'aliases': [], 'difficulty': [7, 12.75], 'artist': 'MELOIMAGE', 'song_package': 'Cherry'},
    'hunted[Cherry]': {'aliases': [], 'difficulty': [6, 13.0], 'artist': 'Night Keepers feat Sylvia',
                       'song_package': 'Cherry'},
    'Capture me[Cherry]': {'aliases': [], 'difficulty': [7, 11.25], 'artist': 'ヒゲドライバー feat. shully',
                           'song_package': 'Cherry'},
    'Realize[Cherry]': {'aliases': ['意识'], 'difficulty': [8, 12.0], 'artist': 'Persona', 'song_package': 'Cherry'},
    'Turnstile Jumper[JOE]': {'aliases': [], 'difficulty': [7, 13.5], 'artist': 'Frums', 'song_package': 'JOE'},
    'Juicy Gossip[JOE]': {'aliases': [], 'difficulty': [7, 11.75], 'artist': 'good-cool', 'song_package': 'JOE'},
    'Standby for Action[JOE]': {'aliases': [], 'difficulty': [8, 12.25], 'artist': '3R2', 'song_package': 'JOE'},
    'Open the Game[JOE]': {'aliases': ['开游戏'], 'difficulty': [6, 13.0], 'artist': 'Jiro', 'song_package': 'JOE'},
    'Hydrangea[JOE]': {'aliases': ['绣球花'], 'difficulty': [6, 12.5], 'artist': 'Tatsh', 'song_package': 'JOE'},
    'Hydrangea(Glitch)[JOE]': {'aliases': [], 'difficulty': [14.25], 'artist': 'Tatsh', 'song_package': 'JOE & CAPSO!'},
    'Absolutely[JOE]': {'aliases': [], 'difficulty': [5, 11.5], 'artist': 'Shi Kuang Lee & Pico',
                        'song_package': 'JOE'},
    'Higher and Higher[JOE]': {'aliases': ['再高一点'], 'difficulty': [6, 13.5], 'artist': 'Jiro', 'song_package': 'JOE'},
    'Take me to the Future[JOE]': {'aliases': ['xj结婚曲'], 'difficulty': [7, 13.75], 'artist': 'Haamoja',
                                   'song_package': 'JOE'},
    'Nautilus[JOE]': {'aliases': ['鹦鹉螺'], 'difficulty': [5, 11.25], 'artist': 'satella', 'song_package': 'JOE'},
    'Bass Music[JOE]': {'aliases': ['贝斯'], 'difficulty': [8, 13.25], 'artist': 'Umziky', 'song_package': 'JOE'},
    'Amenemhat[Sagar]': {'aliases': [], 'difficulty': [8, 13.5], 'artist': 'Yesod (litmus* + Rabbit House + A. Ki)',
                         'song_package': 'Sagar'},
    'Elysium[Sagar]': {'aliases': ['极境'], 'difficulty': [6, 12.0], 'artist': 'SprightS', 'song_package': 'Sagar'},
    'Immram Brain[Sagar]': {'aliases': ['帆', '⛵'], 'difficulty': [6, 13.25], 'artist': '大嶋啓之', 'song_package': 'Sagar'},
    'Space Alien[Sagar]': {'aliases': ['外星人', '👽'], 'difficulty': [8, 13.75], 'artist': 'SADA 2Futureanthem',
                           'song_package': 'Sagar'},
    'Doldrums[Sagar]': {'aliases': ['中东蹦迪'], 'difficulty': [7, 14.0], 'artist': 'Paul Bazooka',
                        'song_package': 'Sagar'},
    'Nídhögg[Sagar]': {'aliases': ['尼德霍格', 'nidhogg', '黑龙', '龙'], 'difficulty': [9, 13.75],
                       'artist': '溝口ゆうま feat. 大瀬良あい', 'song_package': 'Sagar'},
    'Legacy[Sagar]': {'aliases': ['遗产'], 'difficulty': [7, 13.0], 'artist': 'technoplanet', 'song_package': 'Sagar'},
    'A Portent of the Silver Wheel[Sagar]': {'aliases': ['银轮', '银盘'], 'difficulty': [7, 13.25], 'artist': 'millstones',
                                             'song_package': 'Sagar'},
    'Sacrifice[Sagar]': {'aliases': ['牺牲', '献祭'], 'difficulty': [7, 13.75], 'artist': 'TERU FOX',
                         'song_package': 'Sagar'},
    'Return of the Lamp[Sagar]': {'aliases': ['灯神', '🧞', '神灯回归'], 'difficulty': [8, 13.5], 'artist': '柳田Ethnica',
                                  'song_package': 'Sagar'},
    'The Siege[Rin]': {'aliases': ['围城'], 'difficulty': [8, 12.25], 'artist': '3R2', 'song_package': 'Rin'},
    'The Grand Debate[Rin]': {'aliases': ['宏辩'], 'difficulty': [7, 12.0], 'artist': 'Sherwin', 'song_package': 'Rin'},
    '三燈火[Rin]': {'aliases': ['三打火', '三灯火'], 'difficulty': [8, 12.5], 'artist': 'yukitoworks', 'song_package': 'Rin'},
    '「妖怪録、我し来にけり。 」[Rin]': {'aliases': ['妖怪录', '妖怪绿'], 'difficulty': [8, 14.25],
                            'artist': 'TEZUKApo11o band ft.ランコ(豚乙女)+OFFICE萬田㈱', 'song_package': 'Rin'},
    'Starry Summoner[Rin]': {'aliases': ['召星'], 'difficulty': [5, 10.75], 'artist': 'アマギセーラ', 'song_package': 'Rin'},
    'すゝめ☆クノイチの巻[Rin]': {'aliases': ['卷', '女忍者', '手里剑'], 'difficulty': [9, 14.5], 'artist': '黒沢ダイスケ x mitsu feat. ななひら',
                        'song_package': 'Rin'},
    '彩[Rin]': {'aliases': ['菜'], 'difficulty': [9, 15.25], 'artist': 'MisoilePunch♪', 'song_package': 'Rin'},
    '決戦[Rin]': {'aliases': ['决战', '先辈'], 'difficulty': [7, 12.0], 'artist': '篤志', 'song_package': 'Rin'},
    'Mari-Temari[Rin]': {'aliases': ['玛丽特玛丽'], 'difficulty': [6, 12.5], 'artist': 'Miki Fujimoto',
                         'song_package': 'Rin'},
    'Inari[Rin]': {'aliases': ['稻荷'], 'difficulty': [6, 9.75], 'artist': 'TERU FOX', 'song_package': 'Rin'},
    'change[Aroma]': {'aliases': ['改变'], 'difficulty': [5, 9.5], 'artist': 'Tsukasa', 'song_package': 'Aroma'},
    "No One Can't Stop Me[Aroma]": {'aliases': ['没人不能阻止我'], 'difficulty': [5, 11.0], 'artist': 'MK&Kanae Asaba',
                                    'song_package': 'Aroma'},
    'Spotlight On[Aroma]': {'aliases': ['打光'], 'difficulty': [6, 11.75], 'artist': '林子玹 & 山姆丘 & Xinevsky',
                            'song_package': 'Aroma'},
    'Bring the light[Aroma]': {'aliases': ['带来光亮'], 'difficulty': [5, 9.0], 'artist': 'Night Keepers',
                               'song_package': 'Aroma'},
    'Make U Mine[Aroma]': {'aliases': ['mum', 'np贴贴歌'], 'difficulty': [6, 11.25], 'artist': 'James Landino ft. Jenny',
                           'song_package': 'Aroma'},
    'Anzen Na Kusuri[Aroma]': {'aliases': ['安全药'], 'difficulty': [6, 10.5], 'artist': 'The SxPLAY[菅原紗由理]',
                               'song_package': 'Aroma'},
    '漂流[Aroma]': {'aliases': ['激流', '激流', '快把KIVA按住'], 'difficulty': [7, 14.0], 'artist': 'THE SxPLAY & KIVΛ',
                  'song_package': 'Aroma'},
    'Perspectives[Aroma]': {'aliases': ['透视', '呸'], 'difficulty': [5, 10.5], 'artist': 'KIVΛ & Nikki Simmons',
                            'song_package': 'Aroma'},
    'Perspectives(Glitch)[Aroma]': {'aliases': [], 'difficulty': [13.0], 'artist': 'KIVΛ & Nikki Simmons',
                                    'song_package': 'Aroma & CAPSO!'},
    '風の声[Aroma]': {'aliases': ['风之声', 'kimiの声～'], 'difficulty': [4, 9.25], 'artist': 'Iris x Ruri Matsumura',
                   'song_package': 'Aroma'},
    'Beautiful Lie[Aroma]': {'aliases': ['美丽的谎言'], 'difficulty': [6, 11.0], 'artist': 'MINEXO feat. IMANI',
                             'song_package': 'Aroma'},
    'Accelerator[Nora]': {'aliases': ['加速器Nora', 'Nora加速器'], 'difficulty': [7, 13.75], 'artist': 'DJ Myosuke',
                          'song_package': 'Nora'},
    'Dance till Dawn[Nora]': {'aliases': ['三倍ice cream', '三倍⭐ice cream！'], 'difficulty': [6, 10.75],
                              'artist': 'lixound', 'song_package': 'Nora'},
    'Uranus[Nora]': {'aliases': ['天王星'], 'difficulty': [8, 12.0], 'artist': 'MK', 'song_package': 'Nora'},
    'Drop The World[Nora]': {'aliases': ['dtw', '放下世界'], 'difficulty': [8, 14.5], 'artist': 'RiraN',
                             'song_package': 'Nora'},
    'Starlight[Nora]': {'aliases': ['星光'], 'difficulty': [6, 11.0], 'artist': '3R2 & KIVΛ', 'song_package': 'Nora'},
    'Bastard of Hardcore[Nora]': {'aliases': ['硬核混蛋'], 'difficulty': [7, 13.25], 'artist': 'Dj Grimoire',
                                  'song_package': 'Nora'},
    'Jakarta PROGRESSION[Nora]': {'aliases': ['jakarta', '雅加达'], 'difficulty': [8, 14.5], 'artist': 'KURORAK',
                                  'song_package': 'Nora'},
    'Eternity[Nora]': {'aliases': ['永恒'], 'difficulty': [7, 11.25], 'artist': 'Silaver ft.Nathan Brumley',
                       'song_package': 'Nora'},
    'ATONEMENT[Nora]': {'aliases': ['赎罪'], 'difficulty': [6, 11.0], 'artist': 'SIHanatsuka', 'song_package': 'Nora'},
    'Grand Emotion[Nora]': {'aliases': ['荣感'], 'difficulty': [6, 12.0], 'artist': 'Electron', 'song_package': 'Nora'},
    'Chocolate Missile[Neko]': {'aliases': ['巧克力导弹', '糖衣炮弹', '🍫'], 'difficulty': [6, 13.25],
                                'artist': 'Alice Schach and the Magic Orchestra\t', 'song_package': 'Neko'},
    'I can avoid it.#φωφ[Neko]': {'aliases': ['雨中曲', '我能躲它'], 'difficulty': [7, 13.0], 'artist': 'Feryquitous',
                                  'song_package': 'Neko'},
    '一啖兩啖[Neko]': {'aliases': ['一啖两啖', '一吃两吃'], 'difficulty': [7, 12.0], 'artist': '安達 & Sing Sing Rabbit',
                   'song_package': 'Neko'},
    'Mammal[Neko]': {'aliases': ['养猫歌', '猫猫曲'], 'difficulty': [7, 14.0], 'artist': '提供', 'song_package': 'Neko'},
    'Blah!![Neko]': {'aliases': ['吵架歌', '不辣'], 'difficulty': [9, 14.0], 'artist': 'HiTECH NINJA',
                     'song_package': 'Neko'},
    'リラ[Neko]': {'aliases': ['lila'], 'difficulty': [8, 12.25], 'artist': 'Apo11o program ft.moimoi',
                 'song_package': 'Neko'},
    'Log In[Neko]': {'aliases': ['登录', 'login'], 'difficulty': [8, 13.0], 'artist': 'James Landino',
                     'song_package': 'Neko'},
    'Re:incRnaTiØN ～夕焼ケ世界ノ決別ヲ～[Neko]': {'aliases': ['夕烧'], 'difficulty': [6, 16.0],
                                        'artist': 'Apo11o"FILAMENT"program ft. 大瀬良あい×Ritsuka', 'song_package': 'Neko'},
    'R.I.P.[Neko]': {'aliases': ['rip', '🕯️'], 'difficulty': [9, 14.5], 'artist': 'eicateve', 'song_package': 'Neko'}}

cy2_pool_list = []
for i in cy2_pool:
    cy2_pool_list.append(i)

cy2_deleted_song = {}

cy2_horse_music = ['We\'re All Gonna Die[NEKO#ΦωΦ]',
                   'Hydrangea(Glitch)[JOE]',
                   'VIS::CRACKED[Ivy]',
                   'Deadly Slot Game(Glitch)[ROBO_Head]',
                   'Fade Into The Darkness[ROBO_Head]',
                   'Space Alien[Sagar]',
                   'DigiGroove[Ivy]',
                   'Jazzy Glitch Machine[ROBO_Head]',
                   'Midnight[ROBO_Head]',
                   'Open the Game[JOE]',
                   'dimensionalize nervous breakdown[ROBO_Head]',
                   'Higher and Higher[JOE]',
                   'Turnstile Jumper[JOE]',
                   'Deep Dive[Crystal PuNK]',
                   'over the reality[Kizuna AI]',
                   'Cybernetic[Miku]',
                   'Hydrangea[JOE]',
                   'TOKONOMA Spacewalk[NEKO#ΦωΦ]',
                   'I can avoid it.#φωφ[Neko]',
                   'Make Me Burn[ROBO_Head]',
                   'Deadly Slot Game[ROBO_Head]',
                   'Standby for Action[JOE]',
                   'Cityscape[PAFF]',
                   'Malstream[Crystal PuNK]',
                   'Cristalisia[Ivy]',
                   'Chandelier XIII[Crystal PuNK]',
                   'hunted[Cherry]',
                   'Rei[NEKO#ΦωΦ]',
                   'Mari-Temari[Rin]',
                   'Hesitant Blade[NEKO#ΦωΦ]',
                   'Absolutely[JOE]',
                   'Juicy Gossip[JOE]',
                   'Nautilus[JOE]',
                   'I Wish You Were Mine[PAFF]',
                   'Blossoms for Life[PAFF]',
                   'Bullet Waiting for Me[PAFF]',
                   'Make U Mine[Aroma]',
                   'Luolimasi[ROBO_Head]',
                   'The Cross[Crystal PuNK]',
                   'Starry Summoner[Rin]',
                   'Sdorica The Story Unfolds[NEKO#ΦωΦ]',
                   'Winter Games[PAFF]',
                   'Play The Future[NEKO#ΦωΦ]']
